
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

<div class="container">

  <div class="page-header">
  <div class="text-center">
<a class="btn btn-primary" href="controllerAdminCreateTemplate.php">Créer un événement <i class="fa fa-plus"></i></a>

</div>


    <h1>Bonjour <?= $user->get("nom") ?> voici la liste de tout les événements</h1>
  </div>

  <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
    <caption class="sr-only">Explanation of what this complex data table does.</caption>
    <thead>
      <tr>
        <th id="first_name" role="gridcell">Titre</th>
        <th id="last_name" role="gridcell">Type</th>
        <th id="user_role" role="gridcell">Date</th>
        <th role="gridcell" id="user_actions">Actions</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($liste_event as $event){ ?>

<tr>
	<td><?= $event->get("title") ?></td>
	<td><?= $event->get("categorie")->get("categorie") ?></td>
	<td><?= date("d/m/Y",strtotime($event->get("date"))) ?></td>
	<td><a href="controllerAdmindetaille.php?id=<?=$event->get("id") ?>" class="btn btn-primary">Éditer</a></td>
</tr>
<?php } ?>

    <tbody>
  </table>


<div style="margin-top: 80px;">
      <h1>Liste Catégories</h1>
  <table id="autoGeneratedID2" role="grid" class="table table-striped table-bordered">
    <caption class="sr-only">Explanation of what this complex data table does.</caption>
    <thead>
      <tr>
        <th id="first_name" role="gridcell">Numéro de la catégorie</th>
        <th id="last_name" role="gridcell">Nom de la catégorie</th>
        <th role="gridcell" id="user_actions">Actions</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($liste_categorie as $categorie){ ?>

<tr>
	<td><?= $categorie->get("id") ?></td>
	<td><?= $categorie->get("categorie")?></td>

	<td><a href="controllerEditLocastioCategorieTem.php?id=<?=$categorie->get("id") ?>&type=cat" class="btn btn-primary">Éditer</a>
  <a href="controllerDeleteCatLoc.php?id=<?=$categorie->get("id") ?>&type=cat" class="btn btn-primary">Suprimer</a>
</td>
</tr>
<?php } ?>

    <tbody>
  </table>
</div>



<div style="margin-top: 80px;">
      <h1>Liste Localisation</h1>
  <table id="autoGeneratedID3" role="grid" class="table table-striped table-bordered">
    <caption class="sr-only">Explanation of what this complex data table does.</caption>
    <thead>
      <tr>
        <th id="first_name" role="gridcell">Numéro de la localistation</th>
        <th id="last_name" role="gridcell">nom de la localisation</th>
        <th role="gridcell" id="user_actions">Actions</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($liste_location as $location){ ?>

<tr>
	<td><?= $location->get("id") ?></td>
	<td><?= $location->get("location")?></td>

	<td><a href="controllerEditLocastioCategorieTem.php?id=<?=$location->get("id") ?>&type=loc" class="btn btn-primary">Éditer</a>
  <a  href="controllerDeleteCatLoc.php?id=<?=$location->get("id") ?>&type=loc" class="btn btn-primary">Suprimer</a>
</td>
</tr>
<?php } ?>

    <tbody>
  </table>
</div>


</div>











<style>
html {
  font-size: 100%
}

body {
  font-size: 1em
}

p{
 margin-bottom:1em;
}

.btn {
  font-size: 1em
}

.btn-lg{
  line-height: 1.5;
}

.h1, h1 {
  font-size: 2em
}

.h2, h2 {
  font-size: 1.8em
}

.h3, h3 {
  font-size: 1.6em
}

.h4, h4 {
  font-size: 1.4em
}

.h5, h5 {
  font-size: 1.2em
}

.h6, h6 {
  font-size: 1em
}

.nav, .navbar {
  font-size: 1em
}

.navbar-brand {
  font-size: 1.2em
}

.control-label, .form-control, input, label {
  font-size: 1em
}

.form-control {
  padding: .4em .8em;//.375em .75em;
  height: 2.5em;//2.125em
}

.input-lg {
  font-size: 1.2em;
  padding: .625em 1em;
  height: 2.875em
}

.input-sm {
  height: 2.2em;//2em;
  font-size: .85em;
  padding: .3125em .625em
}

.label {
  line-height: 2
}

.badge {
  font-size: .85em;
  min-width: 1em;
  padding: .225em .7em
}

.dropdown-header, .dropdown-menu {
  font-size: 1em
}

.panel-title {
  font-size: 1em
}

.jumbotron {
  font-size: 1em
}

.jumbotron .h1, .jumbotron h1 {
  font-size: 3.9375em
}

.jumbotron p {
  font-size: 1.3125em
}
/*Begin data table tweaks*/
.table button.btn-danger{
  background-color:#661312;
  border-color:#661312;
}
.table button.btn-danger:hover{
  background-color:#912222;
  border-color:#912222;
}
button.btn:hover, button.btn:focus{
  text-decoration:underline;
}
.paginate_button a:hover,
.paginate_button a:focus,
.paginate_button.active a{
  text-decoration:underline;
}
.table-striped > tbody > tr:nth-of-type(2n+1){
  background-color:#f0f0f0;
}
th:focus, td:focus, tr:focus{
  outline: 1px solid #66AFE9;
  box-shadow:0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(102, 175, 233, 0.6);
}
/*Obfuscate all the things!*/
/*td:nth-of-type(-n+3):not(:focus){
  filter: blur(2px);
}*/</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js"></script>



<script>

    $('#autoGeneratedID').dataTable({
  "columnDefs": [
    { "orderable": false, "targets": 3 }
  ]
} );
$('#autoGeneratedID td').attr('role', 'gridcell');
$('#autoGeneratedID tr').attr('role', 'row');
$('#autoGeneratedID th').attr('role', 'gridcell');
$('#autoGeneratedID table').attr('role', 'grid');
$('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');
/*$('#autoGeneratedID').on('page.dt', function(){
  $('#autoGeneratedID tr:nth-of-type(2)').focus();



});*/



$('#autoGeneratedID2').dataTable({
  "columnDefs": [
    { "orderable": false, "targets": 3 }
  ]
} );
$('#autoGeneratedID td').attr('role', 'gridcell');
$('#autoGeneratedID tr').attr('role', 'row');
$('#autoGeneratedID th').attr('role', 'gridcell');
$('#autoGeneratedID table').attr('role', 'grid');
$('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');


$('#autoGeneratedID3').dataTable({
  "columnDefs": [
    { "orderable": false, "targets": 3 }
  ]
} );
$('#autoGeneratedID td').attr('role', 'gridcell');
$('#autoGeneratedID tr').attr('role', 'row');
$('#autoGeneratedID th').attr('role', 'gridcell');
$('#autoGeneratedID table').attr('role', 'grid');
$('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');









  $(".supr").on("click", function(){
    var loc = $(".loc").val();
    if(loc==""){
      alert("vide");
    }else{
      $.ajax("controllerCreateLocation.php", {
        method:"POST",
        data:{
            loc:loc
        },

         success:function(data){

            location.reload();


         }
     });
    }

  })



</script>

